# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1apCo2Ek4xP-AEG4kHfnrXT3WDcORYVaU

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda2.head()

"""# Analsis Exploratorio de los data frame
 - Tipos de Variables
 - Datos duplicada
 - Datos nulos

"""

# Tipos de Variablles Vamos a utilzar el comado Info por Data frame

Tiendas= [tienda, tienda2, tienda3, tienda4]
for tienda in Tiendas:
  print(tienda.info())

"""- Podemos observa que los data frame cuentan con un total de 12 columnas  las cuales contiene variables object (4) y float64 (69) intg(2)

#1. Análisis de facturación
"""

Tiendas = [
    ("Tienda 1", tienda),
    ("Tienda 2", tienda2),
    ("Tienda 3", tienda3),
    ("Tienda 4", tienda4)
]
for nombre, datos in Tiendas:
    total = datos["Precio"].sum()
    print(f"El ingreso total de {nombre} es: ${total:,.1f}")

"""**Observaciones**

- Podemos abservar que La Tienda 2 es la que tiene la mayor facturación, con un ingreso total de $1,116,343,500, superando ligeramente a la Tienda 3.

- Por otra parte podmos ver que las tiendas 1 y 4 tiene un bajo nivel de facturación

# 2. Ventas por categoría

- No contamos con la cantidad de ventas por producto, pero contamos con una variable de datos llamada cuotas pagadas por prodctos basada en la cantidad de cutoas unicas sacaremos cuantas ventas se hicieron de dicho producto.
Agrupar los registros de las categorías con los registros de las cuotas y contar cuántos registros hay de cada combinación.”

- Eso significa que queremos saber:

cuántas ventas hubo dentro de cada categoría y cómo se distribuyen esas ventas según la cantidad de cuotas.
"""

# Lista de tiendas (tuplas con nombre y DataFrame)
Tiendas = [
    ("Tienda 1", tienda),
    ("Tienda 2", tienda2),
    ("Tienda 3", tienda3),
    ("Tienda 4", tienda4)
]

# Bucle para recorrer cada tienda
for nombre, datos in Tiendas:
    print(f"\n📊 Resultados para {nombre}:\n")

    # Agrupar por Categoría, Precio y Cuotas y contar cuántas veces aparece cada combinación
    conteo = (
        datos.groupby(["Categoría del Producto", "Precio", "Cantidad de cuotas"])
        .size()
        .reset_index(name="Total_Transacciones")
    )

    # Mostrar los resultados ordenados
    print(conteo.sort_values(by="Total_Transacciones", ascending=False).head(10))

"""- Para solucionar las ventas por categoria hemos decido agrupar los datos por el numero de registros de la variable (Categoría del Producto, Precio y coutas en las que fueron pagadas)  lo que nos nos hace vaible a un analisis que pruyecte una solucion real

# 3. Calificación promedio de la tienda
"""

#Vamos a utilizar un bucle for y para agilizar el proceso

Tiendas = [
    ("Tienda 1", tienda),
    ("Tienda 2", tienda2),
    ("Tienda 3", tienda3),
    ("Tienda 4", tienda4)
]

for nombre, datos in Tiendas:
    calificacion_promedio = datos["Calificación"].mean()
    print(f"La calificación promedio de {nombre} es: {calificacion_promedio: 0f}")

"""**Obervaciones**

- 2 y 3 tiene una buena califiacion lo cual proyecta el  porque estan teniedo mejor rendimientos en su facturacion

# 4. Productos más y menos vendidos
"""



"""# 5. Envío promedio por tienda"""

Tiendas = [
    ("Tienda 1", tienda),
    ("Tienda 2", tienda2),
    ("Tienda 3", tienda3),
    ("Tienda 4", tienda4)
]

for nombre, datos in Tiendas:
    Envio_promedio_por_tienda = datos["Costo de envío"].mean()
    print(f"La envio promedio de {nombre} es: {Envio_promedio_por_tienda: 0f}")

"""**Obervaciones**

- Tienda 2 presenta el costo de envío promedio más alto ($25,216.24), lo que podría estar relacionado con mayores distancias de entrega, tipos de productos más pesados o un servicio logístico más costoso.

- Tienda 1 y Tienda 4 tienen costos de envío idénticos y más bajos, lo que sugiere que podrían compartir zona geográfica o proveedor logístico.

- Tienda 3 mantiene un valor intermedio, lo que podría reflejar un equilibrio entre volumen de ventas y costos logísticos.

# Graficos Relevantes para el Cliente
"""

#Los ingresos de la tienda

import matplotlib.pyplot as plt

# Lista de tiendas con sus DataFrames
Tiendas = [
    ("Tienda 1", tienda),
    ("Tienda 2", tienda2),
    ("Tienda 3", tienda3),
    ("Tienda 4", tienda4)
]

# Listas para almacenar nombres e ingresos
nombres_tiendas = []
ingresos_totales = []

# Calcular ingresos de cada tienda
for nombre, datos in Tiendas:
    total = datos["Precio"].sum()
    nombres_tiendas.append(nombre)
    ingresos_totales.append(total)
    print(f"El ingreso total de {nombre} es: ${total:,.1f}")

# Crear gráfico de barras
plt.figure(figsize=(8, 5))
barras = plt.bar(nombres_tiendas, ingresos_totales)

# Añadir etiquetas con los valores encima de las barras
for barra, valor in zip(barras, ingresos_totales):
    plt.text(
        barra.get_x() + barra.get_width() / 2,
        valor + 20000000,
        f"${valor:,.0f}",
        ha='center', fontsize=10
    )

# Personalizar gráfico
plt.title("Ingresos Totales por Tienda", fontsize=14)
plt.xlabel("Tiendas", fontsize=12)
plt.ylabel("Ingresos Totales (COP)", fontsize=12)
plt.tight_layout()
plt.show()

# Calificación Promedio por tienda
Tiendas = [
    ("Tienda 1", tienda),
    ("Tienda 2", tienda2),
    ("Tienda 3", tienda3),
    ("Tienda 4", tienda4)
]

# Listas para almacenar resultados
nombres_tiendas = []
calificaciones_promedio = []

    # Calcular promedio de calificaciones
for nombre, datos in Tiendas:
    promedio = datos["Calificación"].mean()
    nombres_tiendas.append(nombre)
    calificaciones_promedio.append(promedio)
    print(f"La calificación promedio de {nombre} es: {promedio:.2f}")

# Crear gráfico de barras
plt.figure(figsize=(8, 5))
barras = plt.bar(nombres_tiendas, calificaciones_promedio, color="#4C72B0")

# Añadir etiquetas encima de las barras
for barra, valor in zip(barras, calificaciones_promedio):
    plt.text(
        barra.get_x() + barra.get_width() / 2,
        valor + 0.05,
        f"{valor:.2f}",
        ha='center',
        fontsize=10
    )

# Personalización del gráfico
plt.title("Calificación Promedio por Tienda", fontsize=14)
plt.xlabel("Tienda", fontsize=12)
plt.ylabel("Calificación Promedio", fontsize=12)
plt.ylim(0, 5)  # Escala de 0 a 5 para las calificaciones
plt.tight_layout()
plt.show()

"""# Informe Final

**Análisis de Tiendas**


El propósito de este análisis fue determinar en cuál tienda debería vender el Sr. Juan, evaluando el desempeño general de cuatro tiendas con base en indicadores clave: ingresos totales, calificaciones promedio, productos y categorías más vendidas, y costos de envío.

Desarrollo del análisis

Ingresos totales:
La Tienda 2 presenta el mayor nivel de facturación con $1,116,343,500, superando al resto de las tiendas. Esto sugiere una alta capacidad de venta y rotación de productos.

Calificación promedio:
Las calificaciones se mantienen estables entre 3.99 y 4.04, siendo nuevamente la Tienda 2 la mejor valorada con 4.04, lo que indica una buena experiencia del cliente.

Categorías más vendidas:
Se observó una mayor concentración de ventas en Electrónicos y Electrodomésticos, reflejando una fuerte demanda por productos tecnológicos.

Costo de envío promedio:
La Tienda 2 también lidera con un costo de envío promedio ligeramente superior ($25,216), lo cual puede explicarse por su volumen de operaciones y cobertura más amplia.

**Conclusión**

Con base en los indicadores analizados, se recomienda que el Sr. Juan venda sus productos en la Tienda 2, ya que combina mayores ingresos, buena reputación y una base sólida de clientes satisfechos.
Esta tienda demuestra el mejor equilibrio entre rentabilidad, satisfacción del cliente y volumen de ventas, lo que la posiciona como la opción más estratégica para incrementar sus oportunidades comerciales.
"""